name: CI

on:
  push:
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        locale: [ "en_US.utf8", "fr_FR.utf8" ]

    env:
      LANG: ${{ matrix.locale }}
      MAVEN_ARGS: "--no-transfer-progress -Dstyle.color=always"
      CONTAINER_REPO: ${{ env.REGISTRY }}
      CONTAINER_REGISTRY_USER: ${{ github.actor }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set locale to ${{ matrix.locale }}
      run: |
        lang=`echo "${{ matrix.locale }}" | head -c 2`
        sudo apt-get -qq install -y language-pack-${lang}
        
        echo ""
        
        # list installed locales
        echo "Available locales"
        locale -a
        sudo locale-gen ${{ matrix.locale }}
        sudo update-locale LANG=${{ matrix.locale }}

    - run: date

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Test project with Maven
      run: |
        mvn $MAVEN_ARGS test package

    - name: Build container image tarball
      run: |
        MAVEN_SKIP_ARGS="-Dmaven.test.skip=true -Dmaven.source.skip=true"
        mvn $MAVEN_ARGS $MAVEN_SKIP_ARGS package jib:buildTar

  cli-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run CLI integration tests
        run: ./cli-tests/cli-tests.sh
