name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Test project with Maven
      run: mvn --no-transfer-progress test package

#    - name: Build documentation
#      run: mvn --no-transfer-progress site
#
#    - name: Deploy documentation to Github Pages
#      # only deploy after merging to master
#      if: github.repository_owner == 'OneBusAway' && github.event_name == 'push' && github.ref == 'refs/heads/master'
#      uses: JamesIves/github-pages-deploy-action@v4
#      with:
#        folder: target/site/
